#!/bin/bash

counter=1
answer=""
points=0
dictionary=""
time=0.05
percernt=0


function usage() # Help usage --help
{
	echo "Usage: $ $(basename $0) <parameters>"
	echo
	echo "       PARAMETERS"
	echo "        -d dictionary_file (each line one word)"
	echo "        -t length of dot (default $time seconds)"
	echo "        --help             (this help)"
	echo
	echo "       EXAMPLES"
	echo "        $ $(basename $0) -d words1.txt"
}

while [ ! -z $1 ]; do
	case $1 in
		"-d") shift; dictionary=$1;;
		"-t") shift; time=$1;;

		"-h" | "--help") usage; exit 0;;

		*) usage; exit 1;;
	esac
	shift
done

echo "Train morse code game with dictionary file $dictionary"
echo "Answer «end» to finish"
echo 
echo "Let's go. What are you listening to..."
while true; do
	max=$(wc -l $dictionary | cut -f1 -d" ")					# Number of lines in dictionary
	n=`echo $(rand -M $max -s $(date +%s)) + 1 | bc`     		# From 0 to (M-1)
	w=$(cat $dictionary | sed -n "$n p")
	morsebeep -t $time -m $w
	read -p "$counter) " answer
	percent=`echo $points \* 100 / $counter | bc`
	if [ "${answer,,}" = "${w,,}" ]; then
		points=`echo $points + 1 | bc`
		percent=`echo $points \* 100 / $counter | bc`
		echo "Right. Points $points $percent%"
	else
		if [ "${answer,,}" = "end" ]; then
			echo
			echo "Total score $points"
			exit 0
		else
			echo "ERROR. The answer is $w $percent%"
		fi
	fi
	counter=`echo $counter + 1 | bc`
done
