#!/bin/bash

counter=1
answer=""
points=0

echo "Train morse code game"
echo "Answer end to finish"
echo 
echo "Let's go. What name are you listening to..."
while true; do
	n=$(rand -M 10 -s $(date +%s))	# From 0 to (M-1)
	w=""
	case $n in
		0) w=paris;;
		1) w=roma;;
		2) w=moscu;;
		3) w=tirana;;
		4) w=yerevan;;
		5) w=baku;;
		6) w=sofia;;
		7) w=nicosia;;
		8) w=prague;;
		9) w=riga;;
	esac
	morsebeep -t 0.1 -m $w
	read -p "$counter) " answer
	if [ "${answer,,}" = "$w" ]; then
		points=`echo $points + 1 | bc`
		echo "Right. Points $points"
	else
		if [ "${answer,,}" = "end" ]; then
			echo
			echo "Total score $points"
			exit 0
		else
			echo "ERROR. The answer is $w"
		fi
	fi
	counter=`echo $counter + 1 | bc`
done
